name: "Deploy"

on:
  release:
    types: [released] # triggered on main branch releases

jobs:
  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-dependencies

  deploy:
    name: "Deploy"
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-dependencies
      - name: "🏗️ Build"
        run: yarn build
      - name: "🚀 Deploy"
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.READ_AND_WRITE_REPOS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          user_name: kieranroneill
          user_email: hello@kieranoneill.com
